#!/bin/bash
#
# 0. Environment MUST be loaded with 'dcenv'
# 1. Docker-compose may reference the target directory
#    with the environment variable $targetEnvironmentPath
# 2. Sets the --project-name to directoryName-configuration
#

set -eu

# Executes docker-compose for a specific enviroment named CONFIGURATION
commandLine="docker-compose -f docker-compose.yml -f $configEnvironmentPath/docker-compose.yml --project-name $projectName $@"

echo "Executing: '$commandLine'"
eval "$commandLine"
