#!/bin/bash
#
# Displays the most recent file matching the specified pattern
# e.g. mrfind /home/me/backup\*.sqldump
# NB:  Special characters must be escaped on the command line!
ls -t $1 | head -n 1
